"""Profile Pic added

Revision ID: 554d3b04e50b
Revises: a6ad12ab8556
Create Date: 2023-12-02 17:36:54.538829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554d3b04e50b'
down_revision = 'a6ad12ab8556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
