"""added username

Revision ID: 724dda65fe53
Revises: e101016987af
Create Date: 2023-11-26 15:05:25.309937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724dda65fe53'
down_revision = 'e101016987af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
