"""Corrextion in Naming of a column in Posts Model

Revision ID: e101016987af
Revises: 2d5929bad9c0
Create Date: 2023-11-25 23:14:43.481513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e101016987af'
down_revision = '2d5929bad9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.drop_column('auther')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auther', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
